/* generated by pull.js */
const manifest = {
  "name": "AI特效",
  "description": "集成AI助手，支持DeepSeek等兼容OpenAI接口的模型",
  "tags": [],
  "enabledByDefault": false,
  "userscripts": [],
  "userstyles": [],
  "settings": [{
    "id": "api_url",
    "type": "string",
    "default": "",
    "name": "API接口地址",
    "placeholder": "例如: https://api.deepseek.com/v1"
  }, {
    "id": "api_key",
    "type": "string",
    "default": "",
    "name": "API密钥",
    "placeholder": "sk-..."
  }, {
    "id": "model",
    "type": "string",
    "default": "",
    "name": "模型名称",
    "placeholder": "留空则从API自动获取"
  }]
};
export default manifest;